export const style = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  bgcolor: 'background.paper',
  color: "black",
  maxWidth: "32rem",
  width: "90vw",
  boxShadow: 24,
  paddingX: 2,
  paddingTop: 4,
  paddingBottom: 2,
  borderRadius: "0.5rem",
};